### ISSUE TITLE
createCheckout got not option for store ID and variant

### ISSUE THREAD

**Issue by Kuzat** [NuroDev/lemonsqueezy.ts#10]
Looking at the [documentation](https://docs.lemonsqueezy.com/api/checkouts#create-a-checkout) it seems I need a store ID and variant when creating a checkout, but there are no options in the latest release (0.1.6) to add those options when calling `createCheckout`.

**Comment by NuroDev** [comment]
Related to #8.

This should be fixed in the next release (`0.1.7`) as these options have since been added ([`variant`](https://github.com/NuroDev/lemonsqueezy.ts/blob/main/src/modules/checkout/checkout.types.ts#L251), [`store`](https://github.com/NuroDev/lemonsqueezy.ts/blob/main/src/modules/checkout/checkout.types.ts#L242))
