### ISSUE TITLE
[Feature Request] Export module's types

### ISSUE THREAD

**Issue by madebyfabian** [NuroDev/lemonsqueezy.ts#3]
Hey there! Love the module. Just a general request, I would love to reuse the types from this module in my application. For example I have a "Product" UI component which accepts a "productData" prop that is an object that should reflect the types.

Basically I would like to do:

```ts
import type { RetrieveProductResult } from 'lemonsqueezy.ts'
```

Thanks!

**Comment by NuroDev** [comment]
This is actually already achievable by importing from `/types` instead of the root / index import path.
The reason why I have put the types into a export path & not in the root is because there is a LOT of types exported & I felt like it was spamming / clogging up the root export. This way the root export only exports the client class & all module functions.

```ts
import type { RetrieveProductResult } from 'lemonsqueezy.ts/types';
```

**Comment by madebyfabian** [comment]
@NuroDev Thanks!
